ES-1030: add direct S3 publishing (WIP)
corda/quasar pull request #169
Opened 2023-07-29 12:52 UTC by ronanbrowne

- Add `S3` publishing to the Quasar project, Due to a change in the way we use Artifactory, we will also now publish any libraries which the OS community may need to a location in S3, which also acts as a Maven Repository. `corda-dependencies`  and `corda-dependencies-dev` will be coming private in the near future so external open source consumers will need to resolve dependencies from this new S3 maven repo, Work has already been done to update various Corda projects to consume from here. 

Also, a nightly sync job copies from the Artifactory location to S3, however, for key projects such as this, we should push directly to the S3 location so new versions are available immediately to the OS builds.

Changes include:
- Add needed logic to the `publishing` block in `build.gradle` file.
- Add `publish` task to `Jenkinsfie` (which it's not on the task dependency graph for `artifactoryPublish` task so needs to be explicitly called)
- Pass the needed `-Pmaven.repo.s3` to the publishing stage, which will trigger the new logic in build.gradle
- Formatting to Jenkins file for easier readability, move tasks before properties and spit into a multiline call

There is no functional change to the behavior of this project apart from the addition of S3 publishing introduced by this PR

2023-07-31 08:50 UTC, yarivus requested changes

2023-07-31 08:50 UTC, yarivus commented on .ci/dev/Jenkinsfile
> +          -Pcompilation.allWarningsAsErrors=true \
```suggestion
        sh '''./gradlew clean assemble \
          --no-daemon \
          -Pcompilation.allWarningsAsErrors=true \
```

2023-07-31 08:59 UTC, yarivus approved these changes
LGTM

2023-08-04 14:12 UTC, chrisr3 approved these changes
LGTM

2023-08-04 14:12 UTC, merged